baseURL = "http://elyasimukka.com/"
languageCode = "en-us"
title = "SEO Consultant For Agencies | Technical Online Marketing Services | Optimize Everything"
theme = "raditian-hugo-theme-master"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"


# navigation
[menu]

  [[menu.header]]
  name = "About"
  URL = "#about"
  weight = 2

  # [[menu.header]]
  # name = "Portfolio"
  # URL = "#portfolio"
  # weight = 3

  [[menu.header]]
  name = "Services"
  URL = "#services"
  weight = 3

  [[menu.header]]
  name = "Contact"
  URL = "#contact"
  weight = 4


  [[menu.footer]]
  name = "About"
  URL = "#about"
  weight = 2

  # [[menu.footer]]
  # name = "Portfolio"
  # URL = "#portfolio"
  # weight = 3

  [[menu.footer]]
  name = "Services"
  URL = "#services"
  weight = 3

  [[menu.footer]]
  name = "Contact"
  URL = "#contact"
  weight = 4


[params]

  googleTagManagerID = "GTM-MGKB7TW" # Google Analytics works with Google Tag Manager

  [params.logo]
    text1 = "Elya Simukka"
    text2 = "Consulting"

  [params.footer]
      copyright = "© Elya Simukka. All rights reserved 2020."
      [params.footer.radity_logo]
        x = "img/general/design-and-code-radity.png"
        _2x = "img/general/design-and-code-radity@2x.png"
        alt = "Design & Code - Radity"
